### ISSUE TITLE
Getting ImportError: cannot import name DjangularModuleTemplateView

### ISSUE THREAD

**Issue by whitef0x0** [appliedsec/djangular#32]
Hey I've been getting an Import error in the urls.py of my djangular installation. I've checked that the DjangularModuleTemplateView exists in views.py and tried even changing the import statement but nothing seems to work. Any ideas on what might be happening (Google/SO isn't helping)?

Here's my traceback:

[05/Mar/2015 11:04:24] ERROR [django.request:231] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 619, in is_valid_path
    resolve(path, urlconf)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 494, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/user1/molescope-dev/molescope/urls.py", line 26, in <module>
    url(r'^djangular/', include('djangular.urls')),
  File "/Library/Python/2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/djangular/urls.py", line 2, in <module>
    from .views import DjangularModuleTemplateView
ImportError: cannot import name DjangularModuleTemplateView

**Comment by whitef0x0** [comment]
Resolved. Was due to my python path.
